https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -4.6566e-10,  2.7521e+25],
        [-2.5250e-29,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


### Constructing other types of matrices

In [3]:
# Construct a randomly initialized matrix:
x = torch.rand(5, 3)
print(x)

tensor([[0.5732, 0.8058, 0.1299],
        [0.3318, 0.8010, 0.7998],
        [0.3056, 0.8126, 0.0725],
        [0.9092, 0.4194, 0.7338],
        [0.2676, 0.8069, 0.5658]])


In [4]:
# Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, 
# e.g. dtype, unless new values are provided by user

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.2552, -0.8092, -0.1013],
        [-0.4330, -0.4990,  1.0227],
        [-0.9962,  0.5692, -0.5758],
        [ 0.1799,  1.8543, -2.5183],
        [ 0.1792,  1.1303, -0.0057]])


### Operations in tensors

In [11]:
# Size/Dimensions
print(x.size())

# Addition syntax option one
y = torch.rand(5, 3)
print(x + y)

# Addition syntax option two
print(torch.add(x, y))

# Addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# Addition: in-place
# adds x to y
y.add_(x)
print(y)

torch.Size([5, 3])
tensor([[ 1.5133e+00, -2.4993e-01,  7.7794e-01],
        [ 4.7119e-02, -1.2462e-01,  1.5410e+00],
        [-9.4180e-01,  8.6051e-01,  2.1240e-03],
        [ 8.0745e-01,  2.2514e+00, -1.9936e+00],
        [ 9.3317e-01,  1.2881e+00,  9.0628e-01]])
tensor([[ 1.5133e+00, -2.4993e-01,  7.7794e-01],
        [ 4.7119e-02, -1.2462e-01,  1.5410e+00],
        [-9.4180e-01,  8.6051e-01,  2.1240e-03],
        [ 8.0745e-01,  2.2514e+00, -1.9936e+00],
        [ 9.3317e-01,  1.2881e+00,  9.0628e-01]])
tensor([[ 1.5133e+00, -2.4993e-01,  7.7794e-01],
        [ 4.7119e-02, -1.2462e-01,  1.5410e+00],
        [-9.4180e-01,  8.6051e-01,  2.1240e-03],
        [ 8.0745e-01,  2.2514e+00, -1.9936e+00],
        [ 9.3317e-01,  1.2881e+00,  9.0628e-01]])
tensor([[ 1.5133e+00, -2.4993e-01,  7.7794e-01],
        [ 4.7119e-02, -1.2462e-01,  1.5410e+00],
        [-9.4180e-01,  8.6051e-01,  2.1240e-03],
        [ 8.0745e-01,  2.2514e+00, -1.9936e+00],
        [ 9.3317e-01,  1.2881e+00,  9.0628e-01]

In [12]:
# You can use standard NumPy-like indexing with all bells and whistles!
print(x[:, 1])

tensor([-0.8092, -0.4990,  0.5692,  1.8543,  1.1303])


In [13]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1011])
0.10113462060689926


### Numpy Compatibility 

In [15]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!